<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL?>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Wawa's</title>
</head>
<body>
    <header>
        <h1>Wawa's</h1>
        <nav>
            <ul>
                <li><a href="home">Home</a></li>
                <li><a href="productos">Productos</a></li>
                <li><a href="about">Sobre Nosotros</a></li>
            </ul>
        </nav>
    </header>
</body>
</html>